sonar.sources=src
sonar.tests=src,tests/e2e
sonar.test.inclusions=**/*.spec.ts,tests/e2e/**/*.ts
sonar.exclusions=dist/**,node_modules/**,tests/performance/**
sonar.coverage.exclusions=src/main.ts,src/**/*.module.ts
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
